inherit_from: .rubocop_todo.yml


Naming/HeredocDelimiterNaming:
  Exclude:
    - 'spec/**/solution_spec.rb'

Naming/VariableNumber:
  EnforcedStyle: snake_case

Metrics/BlockLength:
  Exclude:
    - 'spec/**/solution_spec.rb'

Style/Documentation:
  Enabled: false
